feat(server): Server should periodically delete old builds
GoogleChrome/lighthouse-ci pull request #471
Opened 2020-10-15 11:14 UTC by koh110

I add cron task that delete old builds on sql to the server.

fixes: https://github.com/GoogleChrome/lighthouse-ci/issues/463

2020-10-15 17:18 UTC, patrickhulce requested changes
thank you @koh110 this is fantastic!! 🎉 

those tests and refactor to share cron utils are great 💯

2020-10-15 17:18 UTC, patrickhulce commented on packages/server/src/server.js
> +  startDeletingOldBuildsCron(storageMethod, options);
for consistency with option proposed name `startDeleteOldBuildsCron`?

2020-10-15 17:18 UTC, patrickhulce commented on packages/server/src/cron/delete-old-builds.js
> +'use strict';
could you add a license comment to the top of this file? you can copy/paste from the psi-collect one :)

2020-10-17 16:12 UTC, koh110 commented on packages/server/src/cron/delete-old-builds.js
> +  const runAt = new Date(now.setDate(now.getDate() + range));
I agree with your comment. 
> I worry it relies on a bit too much knowledge of range needing to be negative in config

Your code looks to be easier than my code to understand. Thanks for the good suggestions.

I will change it.

2020-10-17 16:13 UTC, koh110 commented on types/collect.d.ts
> -        autodiscoverUrlBlocklist?: string | string[];
This is my mistake! I overlooked that. Thanks.

2020-10-17 16:16 UTC, koh110 commented on types/server.d.ts
> +        deleteOldBuilds?: {
This function only works when the storage option is 'sql', so I put it in `StorageOption`.
But, I agree with your comment. I move up to `Options`.

2020-10-18 19:51 UTC, patrickhulce approved these changes
LGTM thank you @koh110! 🎉

2020-10-18 19:52 UTC, merged

2020-10-19 01:07 UTC, koh110 commented
@patrickhulce Thank you for your review & merge!
I can't wait to use this feature in my lighthouse-ci! Is there anything I can do to help with the release?

2020-10-19 02:34 UTC, patrickhulce commented
Nothing in particular, I'll try to ship it out this week 👍

2020-10-19 03:15 UTC, koh110 commented
I appreciate you! :+1:

2020-11-19 08:59 UTC, emmekappa commented
@patrickhulce any idea when this will be released? Is it planned for the `0.6.2`?

2020-11-19 15:26 UTC, patrickhulce commented
@emmekappa this has been available since v0.5.1

2020-11-21 11:08 UTC, emmekappa commented
@patrickhulce is somehow possible to configure the numbers of days? I cannot see anything in the doc

2020-11-21 17:29 UTC, patrickhulce commented
@emmekappa yes it is, it accepts [two options](https://github.com/GoogleChrome/lighthouse-ci/pull/471/files#diff-d8db0ba89c771e37b3a90bea1b84e676ee6b0d0e31f95b5b420c0a83c8932850R187-R190). `maxAgeInDays` is what you're looking for

It wasn't added to the docs yet, but PR welcome :)