docs: Improve GitHub Actions snippets
GoogleChrome/lighthouse-ci pull request #484
Opened 2020-11-04 21:10 UTC by carloscuesta

Hello! 👋🏼 

Yesterday I was migrating from Travis-CI to GitHub Actions and I found a couple of things that are not mentioned on the docs that could be helpful to include

2020-11-04 21:11 UTC, carloscuesta commented on README.md
> +          ref: ${{ github.event.pull_request.head.sha }}
This is related with the following issue: https://github.com/GoogleChrome/lighthouse-ci/issues/172

2020-11-04 21:12 UTC, carloscuesta commented on README.md
> +          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
This is mentioned on the docs, that you should add the LHCI_GITHUB_APP_TOKEN as an environment variable on the repository but you should include as env inside of the action

2020-11-04 23:36 UTC, patrickhulce requested changes
Thanks for the feedback and improvements @carloscuesta! 🎉 

These two changes are both specific to GitHub status checks and we've tried quite intentionally to avoid including too many future steps in the early parts of the documentation (like the quick start and step 1 of getting started that are changed here.

What do you think of adding this instead under "GitHub Status Checks" section with a special note about ensuring git history is available in *all* CI providers and providing the example for GitHub actions like you've done?

2020-11-05 14:10 UTC, carloscuesta commented
@patrickhulce I think it makes sense! I'm making the updates you suggested, thanks for taking the time to review the PR 😊

2020-11-05 15:22 UTC, patrickhulce approved these changes
thanks @carloscuesta!

2020-11-05 15:22 UTC, merged

2020-11-05 17:38 UTC, carloscuesta commented
You're welcome! Happy to contribute 😊