limit the length of build context for commit messages and authors from ENV too
GoogleChrome/lighthouse-ci pull request #564
Opened 2021-03-01 23:56 UTC by woodhull

whether these strings come from git or ENV they need to be truncated since the upstream server enforces these character limits.

Otherwise, users will get the following exception:

```
Error: Unexpected status code 422
--
  | {"message":"value too long for type character varying(80)"}
  | at ApiClient._convertFetchResponseToReturnValue (/usr/local/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:79:21)
  | at processTicksAndRejections (internal/process/task_queues.js:93:5)
  | at async runLHCITarget (/usr/local/lib/node_modules/@lhci/cli/src/upload/upload.js:409:17)
  | at async Object.runCommand (/usr/local/lib/node_modules/@lhci/cli/src/upload/upload.js:592:16)
  | at async run (/usr/local/lib/node_modules/@lhci/cli/src/cli.js:109:7)
```

2021-03-01 23:58 UTC, woodhull commented
@googlebot I signed it!

2021-03-09 20:34 UTC, patrickhulce reviewed
thanks very much @woodhull! could you add a test case to the build-context.test.js suite? :)

2021-04-12 16:28 UTC, patrickhulce requested changes
just marking this to match the status, let us know if you need more specific pointers on the test case! thanks again :)

2021-04-12 16:39 UTC, woodhull commented
Hi @patrickhulce

Would love to help, but do not have more time to invest at the moment. Feel free to take this PR as a bug report / feature suggestion though or alternatively just close it out.

2021-04-12 21:20 UTC, patrickhulce commented
ah ok no worries, thanks very much for bringing this to our attention and we'll get to it in another PR :)

2021-04-12 21:20 UTC, closed without merging