fix(cli/upload): GithubStatus check fix failedResults/warnResults
GoogleChrome/lighthouse-ci pull request #575
Opened 2021-03-23 14:14 UTC by raphaelbs

This issue happens when `includePassedAssertions` is set as `true`

Relates to raised issue - #570
Inspired from #571

2021-04-12 16:02 UTC, patrickhulce requested changes
thank you so much for this great PR @raphaelbs!

apologies for the delay but I've just returned from leave, future reviews should be faster :)

2021-04-12 17:02 UTC, raphaelbs commented on packages/cli/src/upload/upload.js
> +    }
The debug feels like a dirty hack haha
I'll look into the server fixture

2021-04-23 15:25 UTC, patrickhulce commented
@raphaelbs how are we looking here? need any help?

2021-04-23 15:54 UTC, raphaelbs commented
> @raphaelbs how are we looking here? need any help?

Sorry, I couldn't look it into yet.

2021-04-26 15:25 UTC, metalix2 commented
> > @raphaelbs how are we looking here? need any help?
> 
> Sorry, I couldn't look it into yet.

More than happy to jump in and propose a PR this with the additional changes.. I've been watching this closely the last month. 😅

2021-04-26 15:44 UTC, patrickhulce commented
How does that sound @raphaelbs! If you don't have the bandwidth to finish it up this week, maybe @metalix2 could lend a hand?

Greatly appreciate the work so far, and it's almost there just want to help get it across the finish line! 🏁

2021-04-27 15:22 UTC, raphaelbs commented
> More than happy to jump in and propose a PR this with the additional changes.. I've been watching this closely the last month.

That would be great! I appreciate it @metalix2

2021-04-28 15:38 UTC, metalix2 commented
> > More than happy to jump in and propose a PR this with the additional changes.. I've been watching this closely the last month.
> 
> That would be great! I appreciate it @metalix2

Excellent PR raised! 👍

2021-04-28 18:49 UTC, raphaelbs commented
finishing on #595

2021-04-28 18:49 UTC, closed without merging