Update lighthouse to v7.3.0
GoogleChrome/lighthouse-ci pull request #581
Opened 2021-03-31 10:51 UTC by mattdell

Fixes #580 (severe vulnerability fix) by updating lighthouse version from 7.0.0 to 7.3.0

2021-03-31 10:52 UTC, mattdell commented
@googlebot I signed it!

2021-04-12 16:10 UTC, patrickhulce requested changes
Thanks very much @mattdell! 🎉 

The process for updating the Lighthouse version in this repo though is rather involved and described in the [contributing docs](https://github.com/GoogleChrome/lighthouse-ci/blob/main/CONTRIBUTING.md#updating-the-lighthouse-version). I think in this case with minimal 7.0.0 -> 7.3.0 changes we don't need the full blown version but we need to ensure the `@lhci/utils` and `@lhci/cli` versions match.

2021-04-12 20:10 UTC, patrickhulce approved these changes
thanks for going the extra mile @mattdell! I think you'll need to commit the image snapshots from storyshots that get generated but this LGTM with the changes :)

2021-04-12 20:10 UTC, patrickhulce commented on packages/server/src/ui/routes/build-view/audit-detail/audit-detail-pane.stories.jsx
> +    selectedAuditId={auditPairs700[1].audit.id || ''}
```suggestion
    selectedAuditId={auditPairs730[1].audit.id || ''}
```

2021-04-12 20:10 UTC, patrickhulce commented on packages/server/test/test-utils.js
> +      {...baseBuild, id: '11', hash: '1244', commitMessage: 'build 12', runAt: runAt(10)},
```suggestion
      {...baseBuild, id: '10', hash: '1245', commitMessage: 'build 11', runAt: runAt(11)},
      {...baseBuild, id: '11', hash: '1246', commitMessage: 'build 12', runAt: runAt(12)},
```

2021-04-12 20:13 UTC, mattdell commented
Yeah, struggling with the snapshots...! For some reason when I run them locally I get around 30-40 failures. 🤔

2021-04-12 20:24 UTC, patrickhulce commented
@mattdell I can handle the snapshot updates if you want to revert down to the package/yarn changes so I can push it out today. I'll cherrypick your commits as a base to still get ya the extra cred :)

2021-04-12 20:37 UTC, mattdell commented
Thanks @patrickhulce!

For what it's worth it seems part of the problem is that I'm working within a fork of the original.

<img width="778" alt="Screenshot 2021-04-12 at 21 36 54" src="https://user-images.githubusercontent.com/2536442/114458543-38e90000-9bd7-11eb-8bb4-05086034d3b7.png">

As for the other ones... 🤷🏻‍♂️

2021-04-12 21:10 UTC, merged

2021-04-12 21:11 UTC, patrickhulce commented
thanks @mattdell 🎉