feat: upgrade to Lighthouse 10.1.0
GoogleChrome/lighthouse-ci pull request #899
Opened 2023-04-12 23:38 UTC by adamraine

2023-04-13 18:38 UTC, paulirish requested changes
a couple things i spotted
but overall lookin great

2023-04-13 18:38 UTC, paulirish commented on packages/cli/test/collect.test.js
> +          "Started a web server with "SERVER_START_PORT=XXXX SERVER_START_MESSAGE='Running server' node /Users/asraine/src/lighthouse-ci/packages/cli/test/fixtures/autorun-start-server/autorun-server
i guess this got tweaked by -U but should be ~reverted

2023-04-13 18:38 UTC, paulirish commented on packages/cli/test/collect.test.js
> +          "Started a web server with "SERVER_START_PORT=XXXX SERVER_START_MESSAGE='Running server' node /Users/asraine/src/lighthouse-ci/packages/cli/test/fixtures/autorun-start-server/autorun-server
same

2023-04-13 18:38 UTC, paulirish commented on packages/server/test/ui/__image_snapshots__/storybook-test-jsx-image-storyshots-build-view-audit-detail-pane-version-1010-1-snap.png
something weird here

2023-04-13 18:38 UTC, paulirish commented on packages/server/test/ui/__image_snapshots__/storybook-test-jsx-image-storyshots-build-view-lhr-comparison-version-1010-1-snap.png
something weird here

2023-04-13 20:05 UTC, paulirish commented on packages/server/test/ui/__image_snapshots__/storybook-test-jsx-image-storyshots-build-view-lhr-comparison-version-1010-1-snap.png
this dude?

2023-04-13 20:53 UTC, paulirish approved these changes

2023-04-13 22:03 UTC, merged

2023-04-13 23:08 UTC, chaimabg commented
Hello @adamraine, I wanted to check if this Pull Request will be included in an upcoming release ?

2023-04-14 17:20 UTC, adamraine commented
Yes, we are hoping to do a breaking release today